apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern
  template:
    metadata:
      labels:
        app: mern
    spec:
      containers:
        - name: mern-container
          image: <your-docker-image>
          ports:
            - containerPort: 3000
